apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world
  namespace: depy
spec:
  template:
    metadata:
      name: hello-world-pod
    spec:
      containers:
      - name: hello-world
        image: localhost/hello:latest
      restartPolicy: Never