# apiVersion: v1
# kind: Pod
# metadata:
#   name: hello
#   namespace: depy
# spec:
#   containers:
#   - name: hello
#     image: hello:latest
#     # imagePullPolicy: IfNotPresent
#     imagePullPolicy: Never
#     ports:
#       - containerPort: 3333
#   restartPolicy: Never


apiVersion: v1
kind: Pod
metadata:
  name: hello
  namespace: ing
  labels:
    name: hello
spec:
  containers:
  - name: hello
    image: cbot918/hello
    # imagePullPolicy: Never
    ports:
      - containerPort: 3333
  # restartPolicy: Never